main() {
  int a1 = 1;
  int a2 = 2;
  int a3 = 3;
  int a4 = 4;
  int a5 = 5;
  double q = 1.2;
  double w = 2.3;
  double r = 3.4;
  double u = 5.6;
  double y = 7.8;
  String s1 = "Aluun";
  String s2 = "Akzhigitov";
  String s3 = "Male";
  String s4 = "Apple";
  String s5 = "Hello world";
  bool isTruth = true;
  bool isLie = false;
  bool b3 = true;
  bool b4 = !false;
  bool b5 = false;
  List arr = [1, 2, 3];
  List shoppingList = ["Молоко", "Вода", "Водка"];
  List arr2 = ["lorem", "lorem", "lorem"];
  List arr3 = ["lorem", "lorem", "lorem"];
  List arr4 = ["lorem", "lorem", "lorem"];
  Map peaple1 = {"name": "Aluun", "age": "20"};
  Map peaple2 = {"name": "Lorem", "age": "30"};
  Map peaple3 = {"name": "Lorem", "age": "40"};
  Map peaple4 = {"name": "Lorem", "age": "50"};
  Map peaple5 = {"name": "Lorem", "age": "60"};
  var copyright_symbol = '\u00A9';
  var name = "Anton";
  var age = 15;
  var str = "245";
  var boolean = true;
  Runes symbol2 = new Runes('\u041F');
  Runes symmol3 = new Runes('\u0438');
  Runes symmol4 = new Runes('\u0435');
  Runes symmol5 = new Runes('\u0442');
  dynamic d1 = 15;
  dynamic d2 = true;
  dynamic d3 = 4.2;
  dynamic d4 = [2, 5, 5];
  dynamic d5 = 25;
  final f1;
  final f2;
  final f3;
  final f4;
  final f5;
  const c1 = 3;
  const c2 = 2;
  const c3 = true;
  const c4 = 2.2;
  const c5 = "Lorem";
  f1 = a1;
  f2 = a2;
  f3 = a3;
  f4 = a4;
  f5 = a5;
  d1 = "fifteen";
  d2 = 2;
  d3 = "zero";
  d4 = "hello";
  d5 = false;
  print(
      "bool - $isTruth $isLie $b3 $b4 $b5  ; var - $copyright_symbol $name $age $str $boolean; dynamic - $d1 $d2 $d3 $d4 $d5 ; final - $f1 $f2 $f3 $f4 $f5 ; const - $c1 ; int - $a1 double $q ; string - $s1 ; map - ${peaple1["name"]} ; list - ${shoppingList[0]} ");
}
